USE tabaani_db;

ALTER TABLE posts MODIFY COLUMN content TEXT NULL DEFAULT NULL;

ALTER TABLE posts MODIFY COLUMN image_path TEXT NULL DEFAULT NULL;
ALTER TABLE posts MODIFY COLUMN video_path TEXT NULL DEFAULT NULL;
