USE tabaani_db;

ALTER TABLE posts MODIFY COLUMN content LONGTEXT NULL DEFAULT NULL;
ALTER TABLE posts MODIFY COLUMN image_path LONGTEXT NULL DEFAULT NULL;
ALTER TABLE posts MODIFY COLUMN video_path LONGTEXT NULL DEFAULT NULL;
